development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: d3nbepu15s0alh
  user: tqgiytcadecrvl
  password: MYej_IYwYPXQxU5BE-IJOm7zIU
  pool: 5
  timeout: 5000